[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "rl-benchmark"
version = "0.1.0"
description = "Runtime comparisons between torchforge and Ray"
requires-python = ">=3.11"

# shared dependencies
dependencies = [
    "torch",
    "open_spiel"
]

[project.optional-dependencies]
ray = [
    "ray[default]"
]

forge = [
    "torchforge"
]

[tool.setuptools.packages.find]
where = ["src"]